### PR TITLE
Create ping.pub.json

### PR DESCRIPTION
**Pull request by liangping**

### CODE REVIEW

**Review by rmontagnin — CHANGES_REQUESTED** [review]
@liangping Please submit the updated `genesis.json` file as well

**Comment by liangping** [comment]
OK，



---Original---
From: "Riccardo ***@***.***&gt;
Date: Tue, Apr 20, 2021 16:29 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [desmos-labs/morpheus] Create ping.pub.json (#36)




 
@RiccardoM requested changes on this pull request.
 
@liangping Please submit the updated genesis.json file as well

**Comment by liangping** [comment]
pushed a PR.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Riccardo ***@***.***&gt;; 
发送时间: 2021年4月20日(星期二) 下午4:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [desmos-labs/morpheus] Create ping.pub.json (#36)





 
@RiccardoM requested changes on this pull request.
 
@liangping Please submit the updated genesis.json file as well

**Review by rmontagnin — APPROVED** [review]

**Comment by rmontagnin** [comment]
Closing this in favor of #113

**Pull request closed without merging**
