### PR TITLE
Create gentx-estet008.json

### PR DESCRIPTION
**Pull request by estet008**

### CODE REVIEW

**Comment by rmontagnin** [comment]
Closed cause you're a bot

**Comment by estet008** [comment]
I am not a bot, how can I prove it to you?

**Comment by RiccardoM** [comment]
@estet008 We have the suspect that your account, among others, are performing a Sybil attack on the next trying to submit multiple genesis transactions with different fake accounts. 

If you are not a bot, please join our Discord server and perform the task that is asked there: https://discord.gg/yxPRGdq

**Comment by estet008** [comment]
> Closed cause you're a bot

I am not a bot, how can I prove it to you?

**Comment by rmontagnin** [comment]
@estet008 We have the suspect that your account, among others, are performing a Sybil attack on the next trying to submit multiple genesis transactions with different fake accounts. 

If you are not a bot, please join our Discord server and perform the task that is asked there: https://discord.gg/yxPRGdq

**Review by rmontagnin — APPROVED** [review]

**Pull request merged**
