### PR TITLE
Create gentx-zmey.json

### PR DESCRIPTION
**Pull request by xxzMeyxx**

### CODE REVIEW

**Comment by rmontagnin** [comment]
Closed cause you're a bot

**Review by rmontagnin — APPROVED** [review]

**Review by rmontagnin — APPROVED** [review]

**Review by rmontagnin — APPROVED** [review]

**Comment by RiccardoM** [comment]
@xxzMeyxx Please restore the original repository and branch

**Review by rmontagnin — CHANGES_REQUESTED** [review]
@xxzMeyxx Please restore the original repository and branch

**Comment by rmontagnin** [comment]
Please do not open multiple PRs. 

Closing this as duplicate of #154.

**Pull request closed without merging**
