### PR TITLE
Create gentx-martorit9nin.json

### PR DESCRIPTION
**Pull request by martorit9nin**

### CODE REVIEW

**Comment by rmontagnin** [comment]
Closed cause you're a bot

**Comment by martorit9nin** [comment]
I'm not a bot, open the branch back

**Comment by martorit9nin** [comment]
> Закрыто, потому что ты бот

I'm not bot

**Comment by rmontagnin** [comment]
@Martorit9nin We have the suspect that your account, among others, are performing a Sybil attack on the next trying to submit multiple genesis transactions with different fake accounts. 

If you are not a bot, please join our Discord server and perform the task that is asked there: https://discord.gg/yxPRGdq

**Comment by martorit9nin** [comment]
ok, I've joined discord, only I've already created a new branch at number 109

**Comment by rmontagnin** [comment]
> ok, I've joined discord, only I've already created a new branch at number 109

Ok, we will consider #109 valid instead of this one

**Comment by martorit9nin** [comment]
> > ок, я присоединился к Discord, только я уже создал новую ветку под номером 109
> 
> Хорошо, мы будем считать действительным [# 109](https://github.com/desmos-labs/morpheus/pull/109) вместо этого

excellent

**Pull request closed without merging**
