### PR TITLE
Create gentx-Dyno.json

### PR DESCRIPTION
**Pull request by 0xSugar**

### CODE REVIEW

**Review by rmontagnin — CHANGES_REQUESTED** [review]
@0xSugar Please restore the deleted repository and branch otherwise I won't be able to fix the conflicts and merge your PR

**Comment by rmontagnin** [comment]
Closed cause you're a bot

**Comment by 0xSugar** [comment]
oops, what? 0_0 I'm a bot.. what? Lol

**Comment by rmontagnin** [comment]
@0xSugar We have the suspect that your account, among others, are performing a Sybil attack on the next trying to submit multiple genesis transactions with different fake accounts. 

If you are not a bot, please join our Discord server and perform the task that is asked there: https://discord.gg/yxPRGdq

**Comment by 0xSugar** [comment]
Okay, rn I'm going to market, so I will do everything in.. about 3 hours.

**Comment by 0xSugar** [comment]
Done, sent a message to leobragaz#3226

**Pull request closed without merging**
