### PR TITLE
Create gentx-andriy_desmos.json

### PR DESCRIPTION
**Pull request by AndreyZ1**

### CODE REVIEW

**Comment by rmontagnin** [comment]
@AndreyZ1 We have the suspect that your account, among others, are performing a Sybil attack on the next trying to submit multiple genesis transactions with different fake accounts. 

If you are not a bot, please join our Discord server and perform the task that is asked there: https://discord.gg/yxPRGdq

**Comment by AndreyZ1** [comment]
Hi @RiccardoM I have just sent message to leobragaz#3226 in discord,

**Comment by rmontagnin** [comment]
> Hi @RiccardoM I have just sent message to leobragaz#3226 in discord,

Ok, he will update this PR later once he verified you properly. Then I will be able to merge it

**Comment by AndreyZ1** [comment]
@RiccardoM gotcha, thanks!

**Review by rmontagnin — APPROVED** [review]

**Review by rmontagnin — APPROVED** [review]

**Pull request merged**
