### PR TITLE
Create gentx-wanny.json

### PR DESCRIPTION
**Pull request by CryptoWanny**

### CODE REVIEW

**Comment by rmontagnin** [comment]
Closed cause you're a bot

**Comment by CryptoWanny** [comment]
> Closed cause you're a bot

excuse me, Im not a bot

**Comment by rmontagnin** [comment]
> > Closed cause you're a bot
> 
> excuse me, Im not a bot

We have the suspect that your account, among others, are performing a Sybil attack on the next trying to submit multiple genesis transactions with different fake accounts. 

If you are not a bot, please join our Discord server and perform the task that is asked there: https://discord.gg/yxPRGdq

**Comment by CryptoWanny** [comment]
> > > Closed cause you're a bot
> > 
> > 
> > excuse me, Im not a bot
> 
> We have the suspect that your account, among others, are performing a Sybil attack on the next trying to submit multiple genesis transactions with different fake accounts.
> 
> If you are not a bot, please join our Discord server and perform the task that is asked there: https://discord.gg/yxPRGdq

I did

**Review by rmontagnin — APPROVED** [review]

**Review by rmontagnin — APPROVED** [review]

**Review by rmontagnin — APPROVED** [review]

**Pull request merged**
