### PR TITLE
Create gentx-NeBoSVoD.json

### PR DESCRIPTION
**Pull request by martorit9nin**

### CODE REVIEW

**Comment by rmontagnin** [comment]
@Martorit9nin We have the suspect that your account, among others, are performing a Sybil attack on the next trying to submit multiple genesis transactions with different fake accounts. 

If you are not a bot, please join our Discord server and perform the task that is asked there: https://discord.gg/yxPRGdq

**Comment by martorit9nin** [comment]
> @Martorit9nin We have the suspect that your account, among others, are performing a Sybil attack on the next trying to submit multiple genesis transactions with different fake accounts.
> 
> If you are not a bot, please join our Discord server and perform the task that is asked there: https://discord.gg/yxPRGdq

Will you remove the BOT tag from me?

**Comment by rmontagnin** [comment]
> > @Martorit9nin We have the suspect that your account, among others, are performing a Sybil attack on the next trying to submit multiple genesis transactions with different fake accounts.
> > If you are not a bot, please join our Discord server and perform the task that is asked there: https://discord.gg/yxPRGdq
> 
> Will you remove the BOT tag from me?

This will be done once you're verified inside Discord. We're having a lot of people to verify so please hang tight.

**Comment by Martorit9nin** [comment]
> @Martorit9nin We have the suspect that your account, among others, are performing a Sybil attack on the next trying to submit multiple genesis transactions with different fake accounts.
> 
> If you are not a bot, please join our Discord server and perform the task that is asked there: https://discord.gg/yxPRGdq

Please close this branch, I made mistakes in forming the genesis address, so I will send the form again

**Comment by martorit9nin** [comment]
A branch with a lot of errors

**Pull request closed without merging**
