### PR TITLE
Create gentx-maryg.json

### PR DESCRIPTION
**Pull request by MGavrilo**

### CODE REVIEW

**Comment by rmontagnin** [comment]
Closed cause you're a bot

**Comment by MGavrilo** [comment]
HI, i am not a bot, i am just getting an error and trying to complete it
correctly

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

вт, 20 апр. 2021 г. в 13:08, Riccardo Montagnin ***@***.***>:

**Comment by rmontagnin** [comment]
@MGavrilo We have the suspect that your account, among others, are performing a Sybil attack on the next trying to submit multiple genesis transactions with different fake accounts. 

If you are not a bot, please join our Discord server and perform the task that is asked there: https://discord.gg/yxPRGdq

**Review by rmontagnin — APPROVED** [review]

**Comment by rmontagnin** [comment]
@MGavrilo Please do not open multiple PRs. 

Closing this as duplicate of #151.

**Pull request closed without merging**
